AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-manager-aws

  Sample SAM Template for expense-manager-aws

Parameters:
  UsernameSSM:
    Type: String
    Description: Default username for authentication
    Default: /expense-app-manager/auth/username
  PasswordSSM:
    Type: String
    Description: Default password for authentication
    Default: /expense-app-manager/auth/password
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
Resources:
  Table:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: id
        Type: String
  WriteSpendConnectorPost:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: SpendFunction
      Destination:
        Id: Table
      Permissions:
        - Write
  WriteSpendConnectorGet:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: SpendFunctionGet
      Destination:
        Id: Table
      Permissions:
        - Read
  SpendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: handlers/spendHandler.spendHandler
      Environment:
        Variables:
          TABLE_NAME: 
            Ref: Table
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        SpendEventPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /spend
            Method: post
            RestApiId:
              Ref: ServerlessRestApi
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - handlers/spendHandler.ts
  SpendFunctionGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: handlers/spendHandler.getSpendHandler
      Environment:
        Variables:
          TABLE_NAME: 
            Ref: Table
          SSM_USERNAME: "{{resolve:ssm:/expense-app-manager/auth/username}}"
          SSM_PASSWORD: "{{resolve:ssm:/expense-app-manager/auth/password}}"
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        SpendEventGet:
          Type: Api
          Properties:
            Path: /spend
            Method: get
            RestApiId:
              Ref: ServerlessRestApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - handlers/spendHandler.ts


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SpendApi:
    Description: API Gateway endpoint URL for Prod stage for Spend function
    Value: 
      Fn::Sub: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/spend/"
  SpendFunctionArn:
    Description: Spend post Lambda Function ARN
    Value: 
      Fn::GetAtt: SpendFunction.Arn
  SpendFunctionGetArn:
    Description: Spend Get Lambda Function ARN
    Value: 
      Fn::GetAtt: SpendFunctionGet.Arn
  SpendFunctionIamRole:
    Description: Implicit IAM Role created for Spend function
    Value: 
      Fn::GetAtt: SpendFunctionRole.Arn
  SpendFunctionGetIamRole:
    Description: Implicit IAM Role created for Spend Get function
    Value: 
      Fn::GetAtt: SpendFunctionGetRole.Arn